spring.application.name=Bank-Management-System

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/BankDB}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect